config/routes.rb
Rails.application.routes.draw do


    namespace :admin do
        resources :users
        resources :age_requirements
        resources :app_countries
        resources :awards
        resources :categories
        resources :class_levels
        resources :disciplines
        resources :genders
        resources :individuals
        resources :industries
        resources :lessons
        resources :lesson_galleries
        resources :lesson_schedules
        resources :lesson_specifications
        resources :objectives
        resources :organizations
        resources :profiles
        resources :qualifications
        resources :schools_attendeds
        resources :sub_categories
        resources :sub_sub_categories
        resources :tutor_qualifications
        resources :user_types

        root to: "users#index"
    end

    get 'dashboard', to: 'dashboard#index', as: :dashboard
    
    get '/shortlisted_lessons' => 'shortlisted_lessons#index'
    post '/lessons/:id/shortlist' => 'shortlisted_lessons#create', as: :shortlist_lesson
    post '/shortlisted_lessons/delete' => 'shortlisted_lessons#delete', as: :delete_shortlisted_lessons

    get '/inbox' => 'chats#index', as: :chats
    get '/chats/:id' => 'chats#show', as: :chat
    get 'lessons/:id/chats' => 'chats#create', as: :create_chat
    post 'chats/perform-action' => 'chats#perform_action_on_chats', as: :perform_action_on_chats
    get '/chats/:id/star' => 'chats#toggle_chat_star', as: :toggle_chat_star

    post '/chats/:chat_id/messages' => 'messages#create', as: :message
    get 'chats/:id/update-chat-box' => 'messages#update_chat_box', as: :update_chat_box

    post 'lessons/:id/book-with-chat' => 'bookings#create_with_chat', as: :booking_with_chat
    post 'lessons/:id/book-without-chat' => 'bookings#create_without_chat', as: :booking_without_chat
    patch '/bookings/:id/accept' => 'bookings#accept', as: :accept_booking
    get '/bookings/manage' => 'bookings#manage', as: :manage_bookings
    put 'lesson_schedule/:id/bookings/perform-action' => 'bookings#perform_action', as: :perform_action_on_bookings
    delete '/bookings/:id/cancel' => 'bookings#cancel', as: :cancel_booking
    get '/bookings/student/:id/profile' => 'bookings#student_profile', as: :student_profile
    get '/my-lessons/:id/bookings' => 'bookings#lesson_bookings', as: :lesson_bookings
    get '/enrolled-lessons/:id/bookings' => 'bookings#enrolled_lesson_bookings', as: :enrolled_lesson_bookings
    get '/bookings/:id/confirm-payment' => 'bookings#confirm_payment', as: :confirm_payment
    get '/bookings/:id/send-payment-instructions' => 'bookings#send_payment_instructions', as: :send_payment_instructions 
    
    get '/reviews' => 'reviews#index', as: :reviews
    post '/reviews' => 'reviews#create', as: :create_review
    
    post '/reported_users' => 'reported_users#create', as: :reported_user
    
    resources :accounts do
        collection do
            get :verify_account
            get :delete_account
            get :problem_report
            put :confirm_verification
            post :confirm_delete
            post :email_report
        end
    end

    resources :lessons do
        member do
            get :basic_info
            get :lesson_info
            get :work_and_education
            get :awards
            get :rates
            get :other_settings
        end
    end

    resource :search, only: [:show], controller: :search

    resources :categories, only: [:show]
    resources :sub_categories, only: [:show]
    resources :awards, only: [:edit, :update, :destroy]
    resources :after_signup
    resources :profiles, only: [:update]
    resources :app_countries, only: :show
    resources :lesson_galleries, only: [:destroy]

    devise_for :users, controllers: { registrations: "registrations" }

    post '/payment_setting', to: 'accounts#payment'
    get 'select_change', to: 'select_change#index', as: :select_change
    get '/teach_with_us', to: 'static_pages#teach_with_us'
    get '/how_it_works', to: 'static_pages#how_it_works'
    get '/contact_us', to: 'static_pages#contact_us'
    get '/about_us', to: 'static_pages#about_us'
    get '/privacy', to: 'static_pages#privacy'
    get '/terms', to: 'static_pages#terms'
    get '/home', to: 'static_pages#home'
    get '/faq', to: 'static_pages#faq'

    root 'static_pages#home'


end

app/views/shared/_dash_header.html.haml
.row
	.col-md-12
		%h3
			%strong Account Dashboard
		%hr
.row
	.col-md-12
		%h4{ :style => "margin-top: 0 !important;" }
			%strong
				= "Welcome back, #{current_user.try(:profile).try(:profilable).try(:name)}" if current_user.try(:profile).try(:profilable_type).eql?("Organization")
				= "Welcome back, #{current_user.try(:profile).try(:profilable).try(:first_name)}" if current_user.try(:profile).try(:profilable_type).eql?("Individual")
			%br
			%br
			%small
				= "Account Type: #{current_user.try(:profile).try(:profilable_type)} | Status: #{confirmation_status current_user}".html_safe

/ TODO: MESSAGE AND MESSAGE BOARD

app/views/shared/_footer.html.haml
%footer.footer
  .container-footer
    %p
      %ul.list-inline.pull-left{ :style => "margin: 10px 15px 10px 0"}
        %li
          = link_to "#", style: "color: #3b5998" do
            = fa_icon "facebook-official 2x"
        %li
          = link_to "#", style: "color: #1da1f2" do
            = fa_icon "twitter-square 2x"
        %li
          = link_to "#", style: "color: #000000" do
            = fa_icon "instagram 2x"
      %ul.list-unstyled
        %li
          %ul.list-inline
            %li.about-menu{ :style => "padding-left: 0;"}
              = link_to "Privacy&nbsp;&nbsp;".html_safe, privacy_path, style: "color: #000"
            %li
              = link_to "Terms & Conditions", terms_path, style: "color: #000"
        %li.text-muted{ :style => "margin-top: 5px" }
          = "Prevalearn - © #{Date.current.strftime("%Y")}".html_safe

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
	.container
		.navbar-header
			%button{ :type => "button", :class => "navbar-toggle collapsed", :data => { :toggle => "collapse", :target => "header-menu" } }
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to root_path, class: "navbar-brand" do
				= image_tag('logo.png', size: "120x30")
		.collapse.navbar-collapse#header-menu
			%ul.nav.navbar-nav
				%li.dropdown.dropdown-large
					= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
						Categories
						%span.caret
					%ul.dropdown-menu.dropdown-menu-large.row#large
						- Category.order("name ASC").each_slice(5).with_index do |categories, index|
							- if index.eql?(0)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
							- if index.eql?(1)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
							- if index.eql?(2)
								%li.col-sm-3
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
							- if index.eql?(3)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name

							- if index.eql?(4)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name

			%ul.nav.navbar-nav.navbar-right
				%li= link_to 'Teach With Us', teach_with_us_path
				%li.dropdown
					= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
						About
						%span.caret
					%ul.dropdown-menu.text-center
						%li= link_to 'About Us', about_us_path
						%li= link_to 'FAQ', faq_path
						%li= link_to 'Contact Us', contact_us_path
				- if user_signed_in? && current_user.try(:profile).try(:id).present?
					%li.dropdown
						= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
							= current_user.email
							%span.caret
						%ul.dropdown-menu.text-center
							%li
								= link_to dashboard_path do
									= fa_icon 'user', text: 'Dashboard'
							%li
								= link_to chats_path do
									= fa_icon 'envelope-o', text: 'Inbox'
							%li.divider{ :role => "separator" }
							%li
								= link_to destroy_user_session_path, method: :delete do
									= fa_icon 'sign-out', text: 'Log Out'
				- unless user_signed_in?
					= link_to 'Log In', new_user_session_path, class: "btn btn-default navbar-btn navbar-right"

app/views/shared/_listings.html.haml
.row.course_row
	%section.col-sm-12
		- @lessons.each_slice(3) do |three_lessons|
			.row#tile_row
				- three_lessons.each do |lesson|
					- course_pic = lesson.lesson_galleries.first.nil? ? "default.png" : lesson.lesson_galleries.first.photo.url
					.each_lesson.col-md-4.col-sm-6.col-xs-12
						.pic_div
							= image_tag(course_pic, alt: "Course Pic", class: :lesson_pic)
							.lesson_banner
								= image_tag("marketplace/banner.png")
								.center_text
									- prices = lesson.price_range
									- if prices[:lowest]
										- if prices[:multiple_rates]
											%p.range_price
												From #{number_to_currency(prices[:lowest], precision: 0)}
										- else
											%p.single_price= number_to_currency(prices[:lowest], precision: 2)


							=image_tag(lesson.user.profile.avatar.url || "avatar.png", class: :tutor_pic, alt: "Instructor Picture")
							.course_info
								.instructor_name.text_center
									%p= lesson.user.display_name

								.instructor_ed.text_center
									%p=lesson.show_school

							-# <!-- [enter tree work here. if @rating == 1 display tree1.jpg] -->
							.course_rating.text_center
								- average_reviews(lesson).to_i.times do
									= image_tag("marketplace/colored_tree.png", class: 'img-responsive img-circle review_trees')
								- (5 - average_reviews(lesson).to_i).times do
									= image_tag("marketplace/blank_tree.png", class: 'img-responsive img-circle review_trees')
								%p
									%strong (#{lesson.reviews.count})

							%a{ href: "/lessons/#{ lesson.id }" }
								.course_name
									%p=lesson.title
							.course_description
								%hr
								%p
									=truncate(lesson.class_description, length: 123)

app/views/shared/_loading.html.erb
<div class="modal fade" id="loading" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="margin-top: 12em;">
      <div class="modal-body">
        <div>
          <center><%= image_tag 'loading.gif' %> <h1>Processing please wait</h1></center>
        </div>          
      </div>
    </div>
  </div>
</div>

<!-- Thank you for alerting us. We are sorry to hear of your bad experience and will look into the matter as soon as possible. -->

app/views/shared/_modal.html.haml
.modal.fade{ :id => "sharedModal", :tabindex => "-1", :role => "dialog" }
  .modal-dialog{ :role => "document" }
    .modal-content
      .modal-header
        %button{ :type => "button", :class => "close", :data => { :dismiss => "modal" } }
          %span{ :aria => { :hidden => "true" } }
            &times;
        %h4.modal-title{ :id => "sharedModalLabel" }
          Title
      .modal-body
        = "..."

app/views/shared/_search_form.html.haml
= simple_form_for(:search, html: { id: :search, class: "filter_form search_simple_form", method: :get }) do |f|
  .control-group
  = f.error_notification

  .search-form-inputs
    = f.input :code_lat, :as => :hidden, :input_html => { id: "code_lat", value: @latitude }
    = f.input :code_lng, :as => :hidden, :input_html => { id: "code_lng", value: @longitude }
    = f.input :browse_from, class: 'form-control', label: "BROWSE FROM", input_html: {id: "location", value: @location }, include_blank: false, required: false
    = f.input :range_from, class: 'form-control', label: "COURSE DISTANCE", input_html: {value: @range}, placeholder: "Distance in KM", required: false
    #rates_range_inputs
      = f.input :rates_from, class: 'form-control', id: 'rates_range_label', label: "RATES", placeholder:"S$", input_html: {value: @lowest}, required: false
      %p#rates_to to
      = f.input :rates_to, class: 'form-control',label: false, placeholder:"S$",input_html: {value: @highest}, required: false
    = f.input :sort_by, class: 'form-control',label: "SORT BY", collection: {"Last Login" => :last_login, "Nearest to Me" => :nearest, "Lowest Price" => :lowest_price, "Highest Price" => :highest_price}, include_blank: false, selected: @order, required: false
    #search_input
      = f.input :search, label: "SEARCH", id: "search_input", input_html: { class: ['ui-autocomplete-input'], value: @query}, required: false
      .form-actions
      = f.button :button, class: "form-filter-button" do
        %span.glyphicon.glyphicon-search



/-if @lesson_specs
/  %ul{:id => "lessons"}
/    -@lesson_specs.each do |lesson_spec|
/      %li{:address => lesson_spec["class_location"]}
/        =lesson_spec["class_location"]


/  -# =@lesson_spec.first["class_location"]

app/views/shared/_search_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
	.container
		.navbar-header
			%button{ :type => "button", :class => "navbar-toggle collapsed", :data => { :toggle => "collapse", :target => "header-menu" } }
				%span.sr-only Toggle navigation
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to root_path, class: "navbar-brand" do
				= image_tag('logo.png', size: "120x30")
		.collapse.navbar-collapse#header-menu
			%ul.nav.navbar-nav
				%li.dropdown.dropdown-large
					= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
						Categories
						%span.caret
					%ul.dropdown-menu.dropdown-menu-large.row#large
						- Category.order("name ASC").each_slice(5).with_index do |categories, index|
							- if index.eql?(0)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
							- if index.eql?(1)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
							- if index.eql?(2)
								%li.col-sm-3
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
							- if index.eql?(3)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name

							- if index.eql?(4)
								%li.col-sm-2
									%ul
										- categories.each do |c|
											%li
												= link_to category_path(c) do
													= image_tag("categories/#{c.name.downcase.gsub(' ', '-')}.png", size: "20x20")
													= c.name
			.row.header_search_input.text-center#header_search
				%form{ class: "form-inline", action: :search, method: :get, id: :search }
					.form-group.header_search_input
						.input-group{ style: "width: 40vh !important;" }
							.input-group-addon
								= fa_icon "search"
							%input{ type: "text", class: "form-control input-lg ui-autocomplete-input", name: 'search[search]', placeholder: "Piano, Ballet, Yoga..." }
			%ul.nav.navbar-nav.navbar-right
				%li= link_to 'Teach With Us', teach_with_us_path
				%li.dropdown
					= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
						About
						%span.caret
					%ul.dropdown-menu.text-center
						%li= link_to 'About Us', about_us_path
						%li= link_to 'FAQ', faq_path
						%li= link_to 'Contact Us', contact_us_path
				- if user_signed_in? && current_user.try(:profile).try(:id).present?
					%li.dropdown
						= link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
							= current_user.email
							%span.caret
						%ul.dropdown-menu.text-center
							%li
								= link_to dashboard_path do
									= fa_icon 'user', text: 'Dashboard'
							%li
								= link_to chats_path do
									= fa_icon 'envelope-o', text: 'Inbox'
							%li.divider{ :role => "separator" }
							%li
								= link_to destroy_user_session_path, method: :delete do
									= fa_icon 'sign-out', text: 'Log Out'
				- unless user_signed_in?
					= link_to 'Log In', new_user_session_path, class: "btn btn-default navbar-btn navbar-right"

app/views/shared/_side_menu.html.haml
.col-md-3
	%ul.nav.nav-pills.nav-stacked.well
		%li
			= link_to dashboard_path do
				= fa_icon 'cog', text: "&nbsp;&nbsp;Account Settings".html_safe
		%li
			= link_to lessons_path do
				= fa_icon 'user-plus', text: "&nbsp;&nbsp;List a Lesson".html_safe
		%li
			= link_to shortlisted_lessons_path do
				= fa_icon 'heart', text: "&nbsp;&nbsp;My Shortlist".html_safe
		%li
			= link_to manage_bookings_path do
				= fa_icon 'th', text: "&nbsp;&nbsp;Lesson Management".html_safe
		%li
			= link_to reviews_path do
				= fa_icon 'check-circle-o', text: "&nbsp;&nbsp;My Review".html_safe