config/routes.rb
Rails.application.routes.draw do


    namespace :admin do
        resources :users
        resources :age_requirements
        resources :app_countries
        resources :awards
        resources :categories
        resources :class_levels
        resources :disciplines
        resources :genders
        resources :individuals
        resources :industries
        resources :lessons
        resources :lesson_galleries
        resources :lesson_schedules
        resources :lesson_specifications
        resources :objectives
        resources :organizations
        resources :profiles
        resources :qualifications
        resources :schools_attendeds
        resources :sub_categories
        resources :sub_sub_categories
        resources :tutor_qualifications
        resources :user_types

        root to: "users#index"
    end

    get 'dashboard', to: 'dashboard#index', as: :dashboard
    
    get '/shortlisted_lessons' => 'shortlisted_lessons#index'
    post '/lessons/:id/shortlist' => 'shortlisted_lessons#create', as: :shortlist_lesson
    post '/shortlisted_lessons/delete' => 'shortlisted_lessons#delete', as: :delete_shortlisted_lessons

    get '/inbox' => 'chats#index', as: :chats
    get '/chats/:id' => 'chats#show', as: :chat
    get 'lessons/:id/chats' => 'chats#create', as: :create_chat
    post 'chats/perform-action' => 'chats#perform_action_on_chats', as: :perform_action_on_chats
    get '/chats/:id/star' => 'chats#toggle_chat_star', as: :toggle_chat_star

    post '/chats/:chat_id/messages' => 'messages#create', as: :message
    get 'chats/:id/update-chat-box' => 'messages#update_chat_box', as: :update_chat_box

    post 'lessons/:id/book-with-chat' => 'bookings#create_with_chat', as: :booking_with_chat
    post 'lessons/:id/book-without-chat' => 'bookings#create_without_chat', as: :booking_without_chat
    patch '/bookings/:id/accept' => 'bookings#accept', as: :accept_booking
    get '/bookings/manage' => 'bookings#manage', as: :manage_bookings
    put 'lesson_schedule/:id/bookings/perform-action' => 'bookings#perform_action', as: :perform_action_on_bookings
    delete '/bookings/:id/cancel' => 'bookings#cancel', as: :cancel_booking
    get '/bookings/student/:id/profile' => 'bookings#student_profile', as: :student_profile
    get '/my-lessons/:id/bookings' => 'bookings#lesson_bookings', as: :lesson_bookings
    get '/enrolled-lessons/:id/bookings' => 'bookings#enrolled_lesson_bookings', as: :enrolled_lesson_bookings
    get '/bookings/:id/confirm-payment' => 'bookings#confirm_payment', as: :confirm_payment
    get '/bookings/:id/send-payment-instructions' => 'bookings#send_payment_instructions', as: :send_payment_instructions 
    
    get '/reviews' => 'reviews#index', as: :reviews
    post '/reviews' => 'reviews#create', as: :create_review
    
    post '/reported_users' => 'reported_users#create', as: :reported_user
    
    resources :accounts do
        collection do
            get :verify_account
            get :delete_account
            get :problem_report
            put :confirm_verification
            post :confirm_delete
            post :email_report
        end
    end

    resources :lessons do
        member do
            get :basic_info
            get :lesson_info
            get :work_and_education
            get :awards
            get :rates
            get :other_settings
        end
    end

    resource :search, only: [:show], controller: :search

    resources :categories, only: [:show]
    resources :sub_categories, only: [:show]
    resources :awards, only: [:edit, :update, :destroy]
    resources :after_signup
    resources :profiles, only: [:update]
    resources :app_countries, only: :show
    resources :lesson_galleries, only: [:destroy]

    devise_for :users, controllers: { registrations: "registrations" }

    post '/payment_setting', to: 'accounts#payment'
    get 'select_change', to: 'select_change#index', as: :select_change
    get '/teach_with_us', to: 'static_pages#teach_with_us'
    get '/how_it_works', to: 'static_pages#how_it_works'
    get '/contact_us', to: 'static_pages#contact_us'
    get '/about_us', to: 'static_pages#about_us'
    get '/privacy', to: 'static_pages#privacy'
    get '/terms', to: 'static_pages#terms'
    get '/home', to: 'static_pages#home'
    get '/faq', to: 'static_pages#faq'

    root 'static_pages#home'


end

app/models/reported_user.rb
class ReportedUser < ActiveRecord::Base

  belongs_to :reporter, class_name: User
  belongs_to :reportee, class_name: User

  validates_presence_of :reportee_id, :reporter_id, :content

end

app/controllers/reported_users_controller.rb
class ReportedUsersController < ApplicationController
  def create
    @reported_user = ReportedUser.new(reported_user_params)
    @reported_user.save

    respond_to do |format|
      format.js
    end
  end

  private
  def reported_user_params
    params.require(:reported_user).permit(:reporter_id, :reportee_id, :content)
  end
end

app/helpers/reported_users_helper.rb
module ReportedUsersHelper
end

app/views/reported_users/_report_user_form.html.erb
<div class="modal fade" id="report-user-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2>Report a User</h2>
      </div>

      <div class="modal-body report-user-form-body">
        <%= form_tag(reported_user_path, method: 'post', remote: true) do %>
          <b> Help us understand what’s happening.</b>
          
          <%= hidden_field_tag 'reported_user[reporter_id]', current_user.id %>
          <%= hidden_field_tag 'reported_user[reportee_id]', @instructor.try(:id) || chat_title_bar_user.try(:id) %>

          <%= text_area_tag 'reported_user[content]', '', class: 'form-control', style: 'width: 100% !important; resize: none;', rows: '6' %>
          <br />
          <%= submit_tag 'Submit', class: 'btn btn-success', style: 'margin-left: 38%; margin-right: 38%; width: 24%;' %> 
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Thank you for alerting us. We are sorry to hear of your bad experience and will look into the matter as soon as possible. -->

app/views/reported_users/create.js.erb
<% if @reported_user.persisted? %>
  $('.report-user-form-body').html('<p>Thank you for alerting us. We are sorry to hear of your bad experience and will look into the matter as soon as possible.</p>');
<% else %>
  $('.report-user-form-body').html('<p>Something went wrong !!!</p>');
<% end %>    